export const GET_FORM_START = 'GET_FORM_START';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';
export const GET_FORM_FAIL = 'GET_FORM_FAI;';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_FILES = 'UPDATE_FILES';
